# -*- coding: utf-8 -*-
"""Welcome To Colaboratory

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

def index_ganjil(kata):
    return kata[1::2]
input_kata = input("Masukkan sebuah kata: ")
hasil = index_ganjil(input_kata)
print("Karakter Index Ganjil:", hasil)

angka_pertama = int(input("Masukkan angka pertama: "))
angka_kedua = int(input("Masukkan angka kedua: "))
jumlah_range = sum(range(angka_pertama, angka_kedua + 1))

print("Jumlah range adalah:", jumlah_range)