# -*- coding: utf-8 -*-
"""Welcome To Colaboratory

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

print("@@@@ @@@@ @@@@ @@@@@")
print("  @  @    @      @")
print("  @  @@@@ @@@@   @")
print("@ @  @    @      @")
print("@@@@ @@@@ @@@@   @")

def list_to_tuple(input_list):

    result_tuple = tuple(input_list)
    return result_tuple

example_list = [1, 2, 4, 3, 1, 44]

result_tuple = list_to_tuple(example_list)
print("======== ELKOM 1 ========")
print(example_list)
print("Hasil reverse ke tuple:")
print(result_tuple)

def calculate_average(tuple_of_tuples):
    # Menghitung jumlah kolom dan baris dalam tuple
    num_rows = len(tuple_of_tuples)
    num_cols = len(tuple_of_tuples[0])

    # Inisialisasi list untuk menyimpan total setiap kolom
    column_sums = [0] * num_cols

    # Iterasi melalui setiap kolom dan baris, mengakumulasikan nilai
    for row in tuple_of_tuples:
        for col_index, value in enumerate(row[0].split(',')):
            cleaned_value = float(value.replace('*', ''))  # Menghilangkan karakter '*'
            column_sums[col_index] += cleaned_value

    # Menghitung rata-rata untuk setiap kolom
    column_averages = [round(sum_values / num_rows, 1) for sum_values in column_sums]

    return column_averages

# Contoh tuple
example_tuple = (
    ('1021, 1022, 1023', '1025, 1026, 1027', '1029, 1030, 1030'),
    # Tambahkan tuple lain jika diperlukan
)

# Memanggil fungsi dan menampilkan hasil
result_averages = calculate_average(example_tuple)
print("Tuple 1:")
for subtuple in example_tuple:
    print(subtuple)
print("Rata-rata dari tuple adalah:")
print(result_averages)
print("=======Jet Aditya Pratomo=======")
print("========= 064002100036 =========")

def calculate_product(input_list):
    result = 1
    for value in input_list:
        result *= value
    return result

# Contoh list
example_list = [1, 5, 4, 5]

# Memanggil fungsi dan menampilkan hasil
result_product = calculate_product(example_list)
print("ELKOM 3:")
print(example_list)
print(result_product)

def count_matching_strings(input_list):
    matching_strings = [s for s in input_list if isinstance(s, str) and len(s) >= 2 and s[0] == s[-1]]
    return matching_strings

# Contoh list
example_list = ['z', 'xvc', 'cac', 244]

# Memanggil fungsi dan menampilkan hasil
result_strings = count_matching_strings(example_list)

print(example_list)
print("String yang memenuhi syarat:")
for s in result_strings:
    print(f"- {s}")

print(f"Terdapat {len(result_strings)} string yang memenuhi syarat.")